title: Fredrik D. Johansson
url: www.fredjo.com
description: Machine learning researcher Fredrik Johansson at Chalmers University of Technology

twitter:
  username: frejohk
  card: summary

plugins:
  - jekyll-seo-tag
